# About Dataset
Assignment
Your notebooks must contain the following steps:

Perform data cleaning and pre-processing.
What steps did you use in this process and how did you clean your data.
Perform exploratory data analysis on the given dataset.
Explain each and every graphs that you make.
Train a ml-model and evaluate it using different metrics.
Why did you choose that particular model? What was the accuracy?
Hyperparameter optimization and feature selection is a plus.
Model deployment and use of ml-flow is a plus.
Perform model interpretation and show feature importance for your model.
Provide some explanation for the above point.
Future steps.
Note: try to have your notebooks as presentable as possible.
Dataset Description
CSV file - 19237 rows x 18 columns (Includes Price Columns as Target)

Attributes
ID
Price: price of the care(Target Column)
Levy
Manufacturer
Model
Prod. year
Category
Leather interior
Fuel type
Engine volume
Mileage
Cylinders
Gear box type
Drive wheels
Doors
Wheel
Color
Airbags

Confused or have any doubts in the data column values? Check the dataset discussion tab!

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [ ]:
df = pd.read_csv('Data.csv')

In [ ]:
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,Front,04-May,Left wheel,White,12

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19237 non-null  int64
 1   Price             19237 non-null  int64
 2   Levy              19237 non-null  object
 3   Manufacturer      19237 non-null  object
 4   Model             19237 non-null  object
 5   Prod. year        19237 non-null  int64
 6   Category          19237 non-null  object
 7   Leather interior  19237 non-null  object
 8   Fuel type         19237 non-null  object
 9   Engine volume     19237 non-null  object
 10  Mileage           19237 non-null  object
 11  Cylinders         19237 non-null  float64
 12  Gear box type     19237 non-null  object
 13  Drive wheels      19237 non-null  object
 14  Doors             19237 non-null  object
 15  Wheel             19237 non-null  object
 16  Color             19237 non-null  object
 17  Airbags           19237 non-null  int64
dtypes: float64(1), int64(4), object(13)
memory usage: 2.6+ MB

In [ ]:
df.isnull().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
dtype: int64

In [ ]:
df.duplicated().sum()

313

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,18924.0,4.557538e+07,937546.823889,20746880.0,45695007.5,45771914.5,45801742.25,45816654.0
Price,18924.0,1.858744e+04,192135.630726,1.0,5331.0,13172.0,22063.00,26307500.0
Prod. year,18924.0,2.010914e+03,5.665749,1939.0,2009.0,2012.0,2015.00,2020.0
Cylinders,18924.0,4.580216e+00,1.200223,1.0,4.0,4.0,4.00,16.0
Airbags,18924.0,6.568379e+00,4.322323,0.0,4.0,6.0,12.00,16.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18924 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18924 non-null  int64
 1   Price             18924 non-null  int64
 2   Levy              18924 non-null  object
 3   Manufacturer      18924 non-null  object
 4   Model             18924 non-null  object
 5   Prod. year        18924 non-null  int64
 6   Category          18924 non-null  object
 7   Leather interior  18924 non-null  object
 8   Fuel type         18924 non-null  object
 9   Engine volume     18924 non-null  object
 10  Mileage           18924 non-null  object
 11  Cylinders         18924 non-null  float64
 12  Gear box type     18924 non-null  object
 13  Drive wheels      18924 non-null  object
 14  Doors             18924 non-null  object
 15  Wheel             18924 non-null  object
 16  Color             18924 non-null  object
 17  Airbags           18924 non-null  int64
dtypes: float64(1), int64(4), object(13)
memory usage: 2.7+ MB

In [ ]:
df = df.drop(['ID','Doors'], axis =1 )

In [ ]:
df['Levy'] = df['Levy'].str.replace('-','0')

In [ ]:
df['Levy'] = df['Levy'].astype(int)

In [ ]:
df['Engine volume'] = df['Engine volume'].str.replace(' Turbo','')

In [ ]:
df['Engine volume'] = df['Engine volume'].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18924 entries, 0 to 19236
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             18924 non-null  int64
 1   Levy              18924 non-null  int64
 2   Manufacturer      18924 non-null  object
 3   Model             18924 non-null  object
 4   Prod. year        18924 non-null  int64
 5   Category          18924 non-null  object
 6   Leather interior  18924 non-null  object
 7   Fuel type         18924 non-null  object
 8   Engine volume     18924 non-null  float64
 9   Mileage           18924 non-null  object
 10  Cylinders         18924 non-null  float64
 11  Gear box type     18924 non-null  object
 12  Drive wheels      18924 non-null  object
 13  Wheel             18924 non-null  object
 14  Color             18924 non-null  object
 15  Airbags           18924 non-null  int64
dtypes: float64(2), int64(4), object(10)
memory usage: 2.5+ MB

In [ ]:
df['Mileage'] = df['Mileage'].str.replace('km','')

In [ ]:
df['Mileage']= df['Mileage'].astype(float)

In [ ]:
df['Prod. year']

0        2010
1        2011
2        2006
3        2011
4        2014
         ...
19232    1999
19233    2011
19234    2010
19235    2007
19236    2012
Name: Prod. year, Length: 18924, dtype: int64

In [ ]:
df['Age']=df['Prod. year'] = 2024 - df['Prod. year']

In [ ]:
df['Age']

0        14
1        13
2        18
3        13
4        10
         ..
19232    25
19233    13
19234    14
19235    17
19236    12
Name: Age, Length: 18924, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18924 entries, 0 to 19236
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             18924 non-null  int64
 1   Levy              18924 non-null  int64
 2   Manufacturer      18924 non-null  object
 3   Model             18924 non-null  object
 4   Prod. year        18924 non-null  int64
 5   Category          18924 non-null  object
 6   Leather interior  18924 non-null  object
 7   Fuel type         18924 non-null  object
 8   Engine volume     18924 non-null  float64
 9   Mileage           18924 non-null  float64
 10  Cylinders         18924 non-null  float64
 11  Gear box type     18924 non-null  object
 12  Drive wheels      18924 non-null  object
 13  Wheel             18924 non-null  object
 14  Color             18924 non-null  object
 15  Airbags           18924 non-null  int64
 16  Age               18924 non-null  int64
dtypes: float64(3), int64(5), object(9)
memory usage: 2.6+ MB

In [ ]:
#one hot encoder

In [ ]:
df=pd.get_dummies(df,columns=['Manufacturer','Model','Category','Leather interior','Cylinders','Gear box type','Drive wheels','Fuel type','Wheel','Color'])

In [ ]:
df

,Price,Levy,Prod. year,Engine volume,Mileage,Airbags,Age,Manufacturer_ACURA,Manufacturer_ALFA ROMEO,Manufacturer_ASTON MARTIN,...,Color_Green,Color_Grey,Color_Orange,Color_Pink,Color_Purple,Color_Red,Color_Silver,Color_Sky blue,Color_White,Color_Yellow
0,13328,1399,14,3.5,186005.0,12,14,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,16621,1018,13,3.0,192000.0,8,13,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,8467,0,18,1.3,200000.0,2,18,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3607,862,13,2.5,168966.0,0,13,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,11726,446,10,1.3,91901.0,4,10,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8467,0,25,2.0,300000.0,5,25,False,False,False,...,False,False,False,False,False,False,True,False,False,False
19233,15681,831,13,2.4,161600.0,8,13,False,False,False,...,False,False,False,False,False,True,False,False,False,False
19234,26108,836,14,2.0,116365.0,4,14,False,False,False,...,False,True,False,False,False,False,False,False,False,False
19235,5331,1288,17,2.0,51258.0,4,17,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19236,470,753,12,2.4,186923.0,12,12,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
df.isnull().sum()

Price             0
Levy              0
Prod. year        0
Engine volume     0
Mileage           0
                 ..
Color_Red         0
Color_Silver      0
Color_Sky blue    0
Color_White       0
Color_Yellow      0
Length: 1720, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18924 entries, 0 to 19236
Columns: 1720 entries, Price to Color_Yellow
dtypes: bool(1713), float64(2), int64(5)
memory usage: 32.1 MB

In [ ]:
X=df.drop('Price',axis=1)
y=df['Price']

In [ ]:
scale=MinMaxScaler()

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
x_train=scale.fit_transform(x_train)

In [ ]:
x_test=scale.transform(x_test)

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
model.score(x_train,y_train)

0.03666162567810305

In [ ]:
y_pred = model.predict(x_test_scaled)

In [ ]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)